[package]
name = "compack"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "compack"
path = "src/bin/compack.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
dirs = "5.0"
